"""add default image value to Cinema

Revision ID: 324e439acd0b
Revises: 741d348e7536
Create Date: 2025-05-28 13:14:35.732455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324e439acd0b'
down_revision: Union[str, None] = '741d348e7536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('seat_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_reservations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat_reservations')
    # ### end Alembic commands ###
