"""add default image value to Cinema

Revision ID: 741d348e7536
Revises: 86b7523e8135
Create Date: 2025-05-28 10:22:57.057308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741d348e7536'
down_revision: Union[str, None] = '86b7523e8135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harga_makanan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('popcorn_caramel', sa.Integer(), nullable=True),
    sa.Column('popcorn_keju', sa.Integer(), nullable=True),
    sa.Column('sosis_bakar', sa.Integer(), nullable=True),
    sa.Column('cola_dingin', sa.Integer(), nullable=True),
    sa.Column('es_teh_manis', sa.Integer(), nullable=True),
    sa.Column('milkshake_coklat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_harga_makanan'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harga_makanan')
    # ### end Alembic commands ###
